import { AIRPORTS, AIRCRAFT, CATEGORIES, airportById, cash, planeById } from './data.js';
import { selectedPlane, aircraftLock, fleetCapacity, dailyOverhead } from './state.js';
import { contractLock, manifestLock, missionInstruction, missionTarget } from './missions.js';
import { SUPPLIES, BRANCH_FACILITIES, UPGRADES, baseOwned, baseHas, baseCapacity, branchPrice, branchRep, branchLotPrice, effectiveSpec, upgradeCost, townLevel, townStatus, routePlan, missionCargoWeight, serviceQuote } from './operations.js';

const meters = (value,color='#9dab67') => `<span class="supply-meter"><i style="width:${Math.max(0,Math.min(100,value))}%;background:${color}"></i></span>`;
const stat = (label,value) => `<div><small>${label}</small><b>${value}</b></div>`;
const thumb = a => `${import.meta.env.BASE_URL}thumbnails/${a.model}.png`;

export function dispatch(ui,icon,escape) {
  const s=ui.state,f=ui.flight,m=s.mission,p=selectedPlane(s),a=effectiveSpec(p);
  if(m){
    const stops=m.orders?m.stopOrder:[];
    const remaining=m.orders?routePlan(s,m.orders.filter(o=>o.status==='onboard'),m.origin,p,f.position,m.stopOrder):null;
    return `<div class="expanded-content scroll-panel"><div class="operation-heading"><div><span class="eyebrow">${CATEGORIES[m.category].name.toUpperCase()}</span><h2>${escape(m.title)}</h2><p>${escape(missionInstruction(s))}</p></div><button class="primary-button" data-action="close">Continue flight ${icon('arrow')}</button></div>
      <div class="network-metrics">${stat('CONTRACT VALUE',cash(m.reward))}${stat('PAID SO FAR',cash(m.paid||0))}${stat('ABOARD',m.orders?`${missionCargoWeight(m)} kg`:`${Math.round(m.quality)}% quality`)}${stat('NEXT STOP',escape(missionTarget(s).label))}</div>
      ${m.handling?`<div class="dispatch-notice">${icon('clock')} Ground crew need ${Math.ceil(m.handling.remaining)} seconds. Close this panel to resume loading or unloading.</div>`:''}
      ${remaining?`<p class="fuel-estimate ${remaining.fuel>p.fuel?'negative':''}">${icon('fuel')} ${Math.round(p.fuel)} L aboard · estimated ${remaining.fuel} L for the remaining ${remaining.km.toFixed(1)} km route, return to ${escape(airportById(remaining.returnBase).name)}, and reserve.</p>`:''}
      ${m.orders?`<div class="manifest-columns"><div><h3>Remaining delivery sequence</h3><p class="muted">Change the order here at any point during the flight.</p>${stops.map((id,i)=>`<div class="manifest-stop"><span class="stop-number">${i+1}</span><div><b>${escape(airportById(id).name)}</b><small>${m.orders.filter(o=>o.status==='onboard'&&o.destination===id).reduce((n,o)=>n+o.payload,0)} kg to unload</small></div><button class="sequence-button" aria-label="Move stop earlier" data-action="stop-move" data-id="${id}" data-dir="-1" ${i===0||m.handling?'disabled':''}>↑</button><button class="sequence-button" aria-label="Move stop later" data-action="stop-move" data-id="${id}" data-dir="1" ${i===stops.length-1||m.handling?'disabled':''}>↓</button></div>`).join('')}</div><div><h3>Orders on this flight</h3>${m.orders.map(o=>`<div class="manifest-order ${o.status==='delivered'?'delivered':''}">${icon(o.status==='delivered'?'check':'package')}<span><b>${escape(o.title)}</b><small>${escape(airportById(o.destination).name)} · ${o.payload} kg · ${o.status==='delivered'?'Delivered':'Onboard'}</small></span><b>${cash(o.status==='delivered'?o.payment:o.reward)}</b></div>`).join('')}</div></div>`:`<div class="brief-tip">${icon('info')} Next destination: ${escape(missionTarget(s).label)}. ${m.deadline?`${Math.max(0,Math.ceil((m.deadline-m.elapsed)/60))} minutes to target response time.`:''}</div>`}
      <button class="text-button danger" data-action="cancel">Cancel remaining work · −1 reputation · completed deliveries remain paid</button></div>`;
  }
  const origin=ui.dispatchOrigin||'hq',here=f.atAirport(),atOrigin=here?.id===origin,origins=[...new Set(['hq',...Object.keys(s.branches),...s.discovered])];
  const list=s.contracts.filter(c=>(c.origin||'hq')===origin&&(ui.filter==='all'||c.category===ui.filter));
  const selected=list.find(c=>c.id===ui.contractId)||list.find(c=>!contractLock(s,c))||list[0];if(selected)ui.contractId=selected.id;
  ui.manifestIds=(ui.manifestIds||[]).filter(id=>s.contracts.some(c=>c.id===id&&(c.origin||'hq')===origin&&c.category==='cargo'));
  const orders=ui.manifestIds.map(id=>s.contracts.find(c=>c.id===id)),plan=routePlan(s,orders,origin,p),lock=manifestLock(s,orders);
  const singleLock=selected?(selected.category==='cargo'?manifestLock(s,[selected]):contractLock(s,selected)):null;
  return `<div class="dispatch-bar"><label>COLLECTION AIRPORT <select id="dispatch-base">${origins.map(id=>`<option value="${id}" ${id===origin?'selected':''}>${escape(airportById(id).name)}${baseOwned(s,id)?' · Company base':' · Return freight counter'}</option>`).join('')}</select></label><span>${escape(a.name)} · ${Math.round(p.fuel)} / ${a.fuel} L</span><button class="text-button" data-action="refresh">Refresh orders ↻</button></div>
    <div class="expanded-board"><div class="board-main"><div class="filter-row">${['all',...Object.keys(CATEGORIES)].map(cat=>`<button class="filter ${ui.filter===cat?'selected':''}" data-action="filter" data-id="${cat}">${cat==='all'?'All work':CATEGORIES[cat].name.split(' ')[0]}</button>`).join('')}</div><div class="contract-list scroll-panel">${list.map(c=>{
      const added=ui.manifestIds.includes(c.id),reason=contractLock(s,c);
      return `<article class="contract-row expanded-contract ${selected?.id===c.id?'selected':''} ${added?'in-manifest':''}"><button class="contract-selection" data-action="contract" data-id="${c.id}"><span class="contract-icon" style="--badge:${CATEGORIES[c.category].color}">${icon(CATEGORIES[c.category].icon)}</span><span class="contract-text"><b>${c.urgent?'<em class="urgent-tag">URGENT</em> ':''}${escape(c.title)}</b><small>${escape(airportById(c.destination).name)} · ${c.distance.toFixed(1)} km${c.category==='cargo'?` · ${c.payload} kg`:''}</small><span class="contract-category">${escape(reason||'Ready for dispatch')}</span></span></button><span class="contract-reward">${cash(c.reward)}<small>+${c.rep} rep</small></span>${c.category==='cargo'?`<button class="add-order ${added?'selected':''}" data-action="manifest-toggle" data-id="${c.id}" aria-label="${added?'Remove from':'Add to'} manifest">${added?'✓':'＋'}</button>`:''}</article>`;
    }).join('')||'<div class="empty-state">No orders in this category. Return freight appears at discovered airports. Branch terminals add local tours.</div>'}</div></div>
    <aside class="dispatch-planner scroll-panel"><span class="eyebrow">${orders.length?'YOUR CARGO MANIFEST':'FLIGHT BRIEFING'}</span>${orders.length?`<h2>${orders.length} orders, one flight.</h2><div class="planner-stats">${stat('CARGO / AVAILABLE',`${plan.payload} / ${plan.capacity} kg`)}${stat('PAYMENT',cash(plan.reward))}${stat('DELIVERY ROUTE',`${plan.km.toFixed(1)} km`)}${stat('RETURN TO BASE',`${plan.returnKm.toFixed(1)} km`)}</div><p class="fuel-estimate ${plan.fuel>p.fuel?'negative':''}">${icon('fuel')} Estimated fuel: <b>${plan.fuel} L</b>, including return and 20% reserve.</p><h3>Order sequence</h3>${orders.map((o,i)=>`<div class="manifest-stop"><span class="stop-number">${i+1}</span><div><b>${escape(airportById(o.destination).name)}</b><small>${o.payload} kg · ${escape(SUPPLIES[o.supply||'food'].name)}</small></div><button class="sequence-button" aria-label="Move order earlier" data-action="manifest-move" data-id="${o.id}" data-dir="-1" ${i===0?'disabled':''}>↑</button><button class="sequence-button" aria-label="Move order later" data-action="manifest-move" data-id="${o.id}" data-dir="1" ${i===orders.length-1?'disabled':''}>↓</button><button class="sequence-button" aria-label="Remove order" data-action="manifest-toggle" data-id="${o.id}">×</button></div>`).join('')}<p class="muted">Orders for the same airport unload together. Use + to add up to six orders.</p><button class="primary-button" data-action="accept-manifest" ${lock||!atOrigin||f.groundJob?'disabled':''}>Load manifest ${icon('arrow')}</button>${lock?`<p class="lock-reason">${escape(lock)}</p>`:''}`:selected?`<h2>${escape(selected.title)}</h2><p>${escape(selected.description)}</p><div class="planner-stats">${stat('REWARD',cash(selected.reward))}${stat('DESTINATION',escape(airportById(selected.destination).name))}</div><p class="muted">${selected.category==='cargo'?'Use + beside cargo orders to combine several deliveries.':'Specialist missions fly separately.'}</p><button class="primary-button" data-action="accept" data-id="${selected.id}" ${singleLock||!atOrigin||f.groundJob?'disabled':''}>Accept & load ${icon('arrow')}</button>${singleLock?`<p class="lock-reason">${escape(singleLock)}</p>`:''}`:'<h2>A new route awaits.</h2>'}
    ${f.groundJob?`<div class="dispatch-notice">Ground service has ${Math.ceil(f.groundJob.remaining)} seconds left. Close this panel to let the crew finish; your draft manifest stays selected.</div>`:''}${!atOrigin?`<div class="dispatch-notice">Land and park at ${escape(airportById(origin).name)} to collect these orders.</div>`:''}
    ${atOrigin&&a.category==='cargo'?`<div class="fuel-planning"><h3>Balance fuel and cargo</h3><p class="muted">Extra fuel uses payload space. Adding fuel costs money; offloaded fuel earns no refund.</p><label for="dispatch-fuel-target">Fuel target <output id="fuel-target-label">${Math.round(p.fuel)} L</output></label><input id="dispatch-fuel-target" type="range" min="${Math.ceil(a.fuel*.1)}" max="${a.fuel}" value="${Math.round(p.fuel)}"/><button class="secondary-button" data-action="set-fuel" ${f.groundJob?'disabled':''}>Set fuel load</button></div>`:''}</aside></div>`;
}

export function fleet(ui,icon,escape) {
  const s=ui.state,f=ui.flight,here=f.atAirport(),local=here?.id||'hq',owned=!!here&&baseOwned(s,local),tab=ui.fleetTab;
  const header=`<div class="fleet-subheader"><div class="segmented">${[['owned','Your fleet'],['shop','Aircraft market'],['upgrades','Workshop']].map(([id,label])=>`<button class="${tab===id?'selected':''}" data-action="fleet-tab" data-id="${id}">${label}</button>`).join('')}</div><span>${icon('hangar')} ${s.fleet.length} / ${fleetCapacity(s)} network spaces</span></div>`;
  if(tab==='upgrades'){
    const p=s.fleet.find(p=>p.uid===ui.upgradeAircraft)||selectedPlane(s),a=effectiveSpec(p),canWork=owned&&p.location===local&&(baseHas(s,local,'hangar')||baseHas(s,local,'largehangar')||baseHas(s,local,'maintenance'))&&!s.mission&&!f.groundJob;
    return header+`<div class="expanded-content scroll-panel"><div class="operation-heading"><div><span class="eyebrow">AIRCRAFT WORKSHOP</span><h2>Build the aircraft for your route.</h2><p>Upgrades stay with each airframe and apply to handling, fuel, payload, and maintenance.</p></div><select id="upgrade-aircraft" aria-label="Aircraft to upgrade">${s.fleet.map(v=>`<option value="${v.uid}" ${v.uid===p.uid?'selected':''}>${escape(planeById(v.type).name)} · ${escape(airportById(v.location||v.home||'hq').name)}</option>`).join('')}</select></div><div class="network-metrics">${stat('PAYLOAD',`${a.capacity} kg`)}${stat('TANK CAPACITY',`${a.fuel} L`)}${stat('CRUISE',`${Math.round(a.cruise*3.6)} km/h`)}${stat('FUEL BURN',`${Math.round(a.burn*3600)} L/h`)}</div>${!canWork?'<div class="dispatch-notice">Park this aircraft at a company base with a hangar or maintenance shop. Finish its current mission and ground service first.</div>':''}<div class="upgrade-grid">${UPGRADES.map(u=>{
      const installed=p.upgrades.includes(u.id),valid=u.id!=='cargo'||a.category==='cargo',cost=upgradeCost(p,u),after=effectiveSpec({...p,upgrades:[...p.upgrades,u.id]});
      return `<article class="upgrade-card">${icon(u.icon)}<h3>${u.name}</h3><p>${u.description}</p>${!installed&&valid?`<div class="upgrade-comparison"><span>Payload <b>${a.capacity} → ${after.capacity} kg</b></span><span>Fuel <b>${a.fuel} → ${after.fuel} L</b></span><span>Cruise <b>${Math.round(a.cruise*3.6)} → ${Math.round(after.cruise*3.6)} km/h</b></span><span>Fuel burn <b>${Math.round(a.burn*3600)} → ${Math.round(after.burn*3600)} L/h</b></span></div>`:''}<button class="${installed?'secondary-button':'primary-button'}" data-action="upgrade-aircraft" data-id="${p.uid}" data-upgrade="${u.id}" ${installed||!valid||!canWork||s.money<cost?'disabled':''}>${installed?'Installed':valid?`Install · ${cash(cost)}`:'Cargo aircraft only'}</button></article>`;
    }).join('')}</div></div>`;
  }
  const cards=tab==='shop'?AIRCRAFT.map(a=>{
    const lock=aircraftLock(s,a,local);
    return `<article class="aircraft-card"><div class="aircraft-image" style="--plane-color:${a.colors[0]}"><img src="${thumb(a)}" alt="${a.name}" loading="lazy"/><span class="aircraft-class">${a.role}</span></div><div class="aircraft-card-body"><div class="aircraft-title"><h2>${a.name}</h2><span>${cash(a.price)}</span></div><p>${a.description}</p><div class="aircraft-specs">${stat('kg capacity',a.capacity)}${stat('km/h cruise',Math.round(a.cruise*3.6))}${stat('L fuel',a.fuel)}</div><p class="lock-reason">${escape(lock||`Delivered to ${airportById(local).name}`)}</p><button class="primary-button" data-action="buy-plane" data-id="${a.id}" ${lock||!owned||s.mission||f.groundJob?'disabled':''}>Purchase aircraft</button></div></article>`;
  }):s.fleet.map(p=>{
    const a=effectiveSpec(p),active=s.selected===p.uid,localPlane=owned&&p.location===local,fuel=serviceQuote(s,p,'fuel',local),repair=serviceQuote(s,p,'repair',local);
    return `<article class="aircraft-card ${active?'selected-aircraft':''}"><div class="aircraft-image" style="--plane-color:${a.colors[0]}"><img src="${thumb(a)}" alt="${a.name}"/><span class="role-badge" style="--badge:${CATEGORIES[a.category].color}">${active?'DISPATCH AIRCRAFT':a.role}</span></div><div class="aircraft-card-body"><div class="aircraft-title"><h2>${a.name}</h2>${active?icon('check'):''}</div><p>${a.capacity} kg capacity · ${p.hours.toFixed(1)} flight hours</p><small class="aircraft-location">${p.location?`Parked at ${escape(airportById(p.location).name)}`:'In flight'} · Based at ${escape(airportById(p.home).name)}</small><div class="aircraft-status"><span>Fuel <b>${Math.round(p.fuel)} / ${a.fuel} L</b></span>${meters(p.fuel/a.fuel*100)}<span>Airframe <b>${Math.round(p.condition)}%</b></span>${meters(p.condition)}</div><div class="upgrade-tags">${p.upgrades.map(id=>`<span>${UPGRADES.find(u=>u.id===id).name}</span>`).join('')||'<span>Standard configuration</span>'}</div><div class="service-buttons"><button data-action="service-fleet" data-id="${p.uid}" data-service="fuel" ${!localPlane||fuel===0||s.money<fuel||f.groundJob||s.mission?.handling?'disabled':''}>${icon('fuel')} Refuel ${cash(fuel)}</button><button data-action="service-fleet" data-id="${p.uid}" data-service="repair" ${!localPlane||repair===0||s.money<repair||f.groundJob||s.mission?.handling?'disabled':''}>${icon('tool')} Repair ${cash(repair)}</button></div><button class="${active?'secondary-button':'primary-button'}" data-action="select-plane" data-id="${p.uid}" ${active||!localPlane||s.mission||f.groundJob?'disabled':''}>${active?'Currently selected':'Fly this aircraft'}</button>${p.home!==local&&localPlane?`<button class="text-button" data-action="rebase-aircraft" data-id="${p.uid}" ${s.mission||f.groundJob?'disabled':''}>Base this aircraft here · $750</button>`:''}<button class="text-button" data-action="workshop" data-id="${p.uid}">Configure upgrades ${icon('tool')}</button>${!active&&s.fleet.length>1?`<button class="text-button danger" data-action="sell-plane" data-id="${p.uid}" ${!localPlane||s.mission?'disabled':''}>Sell for ${cash(Math.round(planeById(p.type).price*.55*p.condition/100))}</button>`:''}</div></article>`;
  });
  return header+(f.groundJob?`<div class="dispatch-notice">Ground crew need ${Math.ceil(f.groundJob.remaining)} seconds. Close this panel to resume service.</div>`:'')+`<div class="aircraft-grid scroll-panel">${cards.join('')}</div>${!owned?'<div class="panel-note">Park at headquarters or an owned branch to purchase, select, or service aircraft. Aircraft stay at the airport where you leave them.</div>':''}`;
}

export function network(ui,icon,escape) {
  const s=ui.state,here=ui.flight.atAirport(),tab=ui.networkTab||'bases',id=ui.networkAirport||'willow',a=airportById(id),b=s.branches[id],t=s.settlements[id],canBuild=here?.id==='hq'||here?.id===id;
  const header=`<div class="fleet-subheader"><div class="segmented"><button class="${tab==='bases'?'selected':''}" data-action="network-tab" data-id="bases">Branch airports</button><button class="${tab==='towns'?'selected':''}" data-action="network-tab" data-id="towns">Community report</button></div><span>${Object.keys(s.branches).length} branches · ${cash(dailyOverhead(s))} / day</span></div>`;
  if(tab==='towns')return header+`<div class="expanded-content scroll-panel"><div class="operation-heading"><div><span class="eyebrow">THE PLACES YOU CONNECT</span><h2>Every delivery reaches a community.</h2><p>Food and clinic supplies support population growth. Construction supplies advance development and unlock larger freight orders. Stocks are consumed every company day.</p></div></div><div class="community-grid">${Object.entries(s.settlements).sort(([,x],[,y])=>Math.min(x.food,x.medicine)-Math.min(y.food,y.medicine)).map(([id,t])=>{
    const a=airportById(id),level=townLevel(t);
    return `<article class="community-card ${t.food<25||t.medicine<25?'shortage':''}"><div class="community-title"><h3>${escape(a.name)}</h3><span>LV ${level}</span></div><p>${escape(townStatus(t))}</p><div class="detail-row"><span>Residents</span><b>${t.population.toLocaleString()} ${t.growth?`<small class="${t.growth>0?'positive':'negative'}">${t.growth>0?'+':''}${t.growth} / day</small>`:''}</b></div>${Object.entries(SUPPLIES).map(([key,v])=>`<div class="supply-line"><span>${v.name}</span><b>${Math.round(t[key])}%</b>${meters(t[key],t[key]<25?'#ca5346':v.color)}</div>`).join('')}<div class="supply-line"><span>${level===3?'Development complete':`Development towards level ${level+1}`}</span><b>${Math.round(t.development)} / 300</b>${meters(level===3?100:t.development%100,'#558fb5')}</div><small class="muted">${Math.round(t.delivered).toLocaleString()} kg supplied · ${t.lastDelivery?`Last arrival day ${t.lastDelivery}`:'Awaiting your first delivery'}</small><button class="text-button" data-action="network-airport" data-id="${id}">View branch opportunities ${icon('arrow')}</button></article>`;
  }).join('')}</div></div>`;
  const chosen=BRANCH_FACILITIES.find(v=>v.id===ui.branchFacility)||BRANCH_FACILITIES[1];
  return header+`<div class="network-layout"><aside class="network-sidebar scroll-panel"><span class="eyebrow">REGIONAL AIRWORKS</span>${AIRPORTS.filter(a=>a.id!=='hq').map(a=>`<button class="network-location ${a.id===id?'selected':''}" data-action="network-airport" data-id="${a.id}"><span><b>${escape(a.name)}</b><small>${a.region}</small></span><em>${s.branches[a.id]?'OWNED':s.discovered.includes(a.id)?'VISITED':'EXPLORE'}</em></button>`).join('')}</aside><div class="network-detail scroll-panel"><div class="operation-heading"><div><span class="eyebrow">${a.region.toUpperCase()}</span><h2>${escape(a.name)}</h2><p>${a.length} m runway · ${a.biome} · ${t.population.toLocaleString()} residents</p></div><button class="secondary-button" data-action="view-airport" data-id="${id}">View on atlas ${icon('map')}</button></div>${b?`<div class="network-metrics">${stat('AIRCRAFT SPACES',baseCapacity(s,id))}${stat('LOTS',`${b.lots.length} / 6`)}${stat('BASE OVERHEAD',`${cash(160+b.buildings.length*25)} / day`)}${stat('FOUNDED',`Day ${b.founded}`)}</div><div class="branch-build-layout"><div class="branch-catalog">${BRANCH_FACILITIES.map(v=>`<button class="facility-option ${chosen.id===v.id?'selected':''}" data-action="branch-facility" data-id="${v.id}">${icon(v.icon)}<span><b>${v.name}</b><small>${cash(v.cost)}</small></span></button>`).join('')}</div><div><div class="branch-lots">${Array.from({length:6},(_,lot)=>{
    const owned=b.lots.includes(lot),building=b.buildings.find(v=>v.lot===lot),v=building?.id==='dispatch'?{name:'Branch dispatch',icon:'tower'}:BRANCH_FACILITIES.find(v=>v.id===building?.id),adjacent=b.lots.some(n=>Math.abs(n%3-lot%3)+Math.abs(Math.floor(n/3)-Math.floor(lot/3))===1);
    return `<button class="lot ${owned?'owned':''} ${building?'occupied':''} ${!owned&&adjacent?'expandable':''}" data-action="branch-lot" data-id="${lot}" ${!canBuild||building||!owned&&!adjacent?'disabled':''}><small>PARCEL ${lot+1}</small>${building?`${icon(v.icon)}<b>${v.name}</b>`:owned?`${icon('hangar')}<b>Build ${chosen.name}<br/>${cash(chosen.cost)}</b>`:`${icon('map')}<b>${adjacent?`Buy land<br/>${cash(branchLotPrice(b))}`:'Expand towards here'}</b>`}</button>`;
  }).join('')}</div><div class="build-detail"><div><h3>${chosen.name}</h3><p>${chosen.description}</p><small>Choose an empty parcel to build. Outlined parcels expand your branch.</small></div></div></div></div>${!canBuild?`<div class="dispatch-notice">Manage construction while parked at headquarters or at ${escape(a.name)}.</div>`:''}<div class="brief-tip">${icon('info')} Cargo can depart from this branch. A terminal adds scenic passenger flights; a freight store adds bulk orders. Runway length limits which aircraft can be purchased here.</div>`:`<div class="branch-purchase"><span class="eyebrow">ESTABLISH A REGIONAL BASE</span><h3>A foothold in ${escape(a.region)}.</h3><p>Purchase a six-parcel site with a dispatch office, one aircraft stand, and two owned parcels. Build the services you need, then use this airport for local departures and fleet purchases.</p><div class="network-metrics">${stat('PURCHASE PRICE',cash(branchPrice(a)))}${stat('REPUTATION',`${branchRep(a)} required`)}${stat('STARTING OVERHEAD',`${cash(210)} / day`)}</div><button class="primary-button" data-action="buy-branch" data-id="${id}" ${!s.discovered.includes(id)||s.reputation<branchRep(a)||s.money<branchPrice(a)||!canBuild?'disabled':''}>Purchase branch · ${cash(branchPrice(a))}</button><p class="muted">${!s.discovered.includes(id)?'Discover this airport by flying here first.':!canBuild?'Park at headquarters or this airport to sign the purchase.':s.reputation<branchRep(a)?`Build your reputation to ${branchRep(a)}.`:'A fuel depot removes remote service costs and reduces fuel prices.'}</p></div>`}<div class="branch-community-summary"><h3>Community outlook</h3><p>${escape(townStatus(t))} · ${Math.round(t.delivered)} kg supplied · development level ${townLevel(t)}</p>${Object.entries(SUPPLIES).map(([key,v])=>`<div class="supply-line"><span>${v.name}</span><b>${Math.round(t[key])}%</b>${meters(t[key],v.color)}</div>`).join('')}</div></div></div>`;
}
